apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: history-mongodb-pvc
  namespace: ajay-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: history-sc
  
        